# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mvm',
                'doc_host': 'https://bonding-curves.github.io',
                'git_url': 'https://github.com/bonding-curves/mvm',
                'lib_path': 'mvm'},
  'syms': { 'mvm.bathtub': { 'mvm.bathtub.p_bathtub': ('bathtub.html#p_bathtub', 'mvm/bathtub.py'),
                             'mvm.bathtub.s_bathtub': ('bathtub.html#s_bathtub', 'mvm/bathtub.py')},
            'mvm.core': {'mvm.core.foo': ('core.html#foo', 'mvm/core.py')}}}
